"""
Configuration constants for PosseTool.
"""

# Bluesky configuration
BLUESKY_CHAR_LIMIT = 300
BLUESKY_IMAGE_MAX_SIZE = 900 * 1024  # 900KB in bytes
BLUESKY_IMAGE_TARGET_WIDTH = 1200
BLUESKY_IMAGE_TARGET_HEIGHT = 630
BLUESKY_IMAGE_QUALITY_START = 95
BLUESKY_IMAGE_QUALITY_MIN = 10
BLUESKY_IMAGE_QUALITY_STEP = 5
BLUESKY_DESCRIPTION_LIMIT = 200

# Mastodon configuration
MASTODON_CHAR_LIMIT = 500

# Text processing configuration
DEFAULT_MAX_LENGTH = 300 